### ISSUE TITLE
Variable not in scope: (##)

### ISSUE THREAD

**Issue by TheBizzle** [HaskellCNOrg/snaplet-i18n#1]
When I try to depend upon version 0.1.0 of this project, I get this error:

```
    Configuring snaplet-i18n-0.1.0...
    Building snaplet-i18n-0.1.0...
    Preprocessing library snaplet-i18n-0.1.0...
    [1 of 2] Compiling Paths_snaplet_i18n ( .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/autogen/Paths_snaplet_i18n.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Paths_snaplet_i18n.o )
    [2 of 2] Compiling Snap.Snaplet.I18N ( src/Snap/Snaplet/I18N.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Snap/Snaplet/I18N.o )
    
    /tmp/stack21254/snaplet-i18n-0.1.0/src/Snap/Snaplet/I18N.hs:104:26: error:
        Variable not in scope:
          (##) :: [Char] -> I.Splice (Handler b0 b0) -> m a0
    
    /tmp/stack21254/snaplet-i18n-0.1.0/src/Snap/Snaplet/I18N.hs:105:30: error:
        Variable not in scope:
          (##) :: [Char] -> I.Splice (Handler b1 b1) -> m b2
    
    /tmp/stack21254/snaplet-i18n-0.1.0/src/Snap/Snaplet/I18N.hs:150:48: error:
        Variable not in scope: (##) :: [Char] -> T.Text -> Splices T.Text
```

This problem seems reproducible, as well.  For example, [the build reports on Hackage](https://hackage.haskell.org/package/snaplet-i18n-0.1.0/reports/) show compilation repeatedly failing for the same reason.

As far as I understand it, the problem is just that the function `##` is no longer being imported, thanks to some API change in one of the libraries (possibly Heist).

**Comment by freizl** [comment]
Did you try to build with Stack?
It shall work well with lts-3.22 otherwise is not guaranteed yet.
Will try to upgrade in an short term.

Thanks!

**Comment by TheBizzle** [comment]
Yes, I get the error when using Stack.  [Here](https://github.com/TheBizzle/elysium/blob/9b9f27fc4cd90dc404eefea355a34b6a7a140751/elysium.cabal) is the Cabal file that my build is based on.

**Comment by freizl** [comment]
I think it's because you're using lts-7.15 but snaplet-i18n only built successfully with lts-3.22.

I may have time to do upgrade later this month.
Is it too later for your project?
Otherwise PR is really welcome.
